### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by CamusGao** [sonyxperiadev/vendor-qcom-opensource-location#17]
https://github.com/sonyxperiadev/vendor-qcom-opensource-location/blob/98f59cdb6261919dbf9b7a302430edd0ca591d3b/loc_api/loc_api_v02/LocApiV02.cpp#L3192

build error like this:
error: too few arguments to function call, expected 3, have 2
      requestATL(connHandle, agpsType);
      ~~~~~~~~~~                     ^

**Comment by Haxk20** [comment]
@jerpelea Please click the close button :)
