### ISSUE TITLE
Android AOSP Nougat 7.0 Compile error: libloc_api_v02_intermediates/import_includes', missing and no known rule to make it

### ISSUE THREAD

**Issue by rancidfrog** [sonyxperiadev/vendor-qcom-opensource-location#3]
When adding this repo to local manifest:
```
<project path="vendor/qcom/opensource/location" name="vendor-qcom-opensource-location" groups="device" remote="sony" revision="master" />
```
And removing prebuilt gps as in commit: https://github.com/SonyAosp/vendor_qcom/commit/e1512714fa468960a9ea2f9f3a101f8edae8c220

I keep getting compile error:
```
Starting build with ninja
ninja: Entering directory `.'
ninja: error: '/home/.../out/target/product/aries/obj/SHARED_LIBRARIES/libloc_core_intermediates/export_includes', needed by '/home/.../out/target/product/aries/obj/SHARED_LIBRARIES/libloc_api_v02_intermediates/import_includes', missing and no known rule to make it
make: *** [build/core/ninja.mk:154: ninja_wrapper] Error 1
```

**Comment by rancidfrog** [comment]
https://github.com/sonyxperiadev/vendor-qcom-opensource-location/blob/master/loc_api/loc_api_v02/Android.mk#L54 ?

**Comment by belov555** [comment]
error: vendor/qcom/opensource/location/loc_api/ds_api: MODULE.TARGET.SHARED_LIBRARIES.libloc_ds_api already defined by vendor/qcom/opensource/location/ds_api.
How to fix?

**Comment by jerpelea** [comment]
what android version are you building?
did you run repo_update?
are you using the proper build buide,?
